### ISSUE TITLE
Typo in 4.1.4 "Generalized eigenvalue problem"

### ISSUE THREAD

**Issue by MrP123** [kandolfp/MECH-M-DUAL-1-DBM#6]
The word "weakly" should be removed in this sentence

https://github.com/kandolfp/MECH-M-DUAL-1-DBM/blob/0aea7c83387b06c954701fa8ad471002c57d1d03/matrixdc/eigen.qmd#L279

**Comment by kandolfp** [comment]
Thanks, telling me twice. I thought I fixed this already...
